import json
import re
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'public' / 'stickers'
PACK_TS = ROOT / 'src' / 'data' / 'stickers-pack.ts'
SOURCES = [
    Path(r'c:\Users\28622\Downloads\自嘲熊动态表情包37个_小欧大王.docx'),
    Path(r'c:\Users\28622\Downloads\【表情包】审美积积第二弹.docx'),
    Path(r'c:\Users\28622\Downloads\自嘲熊表情包 2.pdf'),
]

URL_RE = re.compile(r'https?://[^\s\"\'<>]+')
TARGET_RE = re.compile(r'Target=\"(https?://[^\"]+)\"')
IMAGE_EXT = ('.jpg', '.jpeg', '.png', '.gif', '.webp')

MIN_SIDE = 80
MAX_SIDE = 520
MAX_AREA = 260_000


def load_pil():
    try:
        from PIL import Image
    except ImportError:
        import subprocess
        subprocess.check_call(['python', '-m', 'pip', 'install', 'pillow', '-q'])
        from PIL import Image
    return Image


def image_ok(data: bytes) -> tuple[bool, str]:
    Image = load_pil()
    from io import BytesIO
    try:
        with Image.open(BytesIO(data)) as im:
            w, h = im.size
    except Exception:
        return False, 'unreadable'
    short, long = min(w, h), max(w, h)
    area = w * h
    if short < MIN_SIDE:
        return False, f'too small {w}x{h}'
    if long > MAX_SIDE:
        return False, f'too large {w}x{h}'
    if area > MAX_AREA:
        return False, f'sheet {w}x{h}'
    if short < 100 and long > short * 3:
        return False, f'banner {w}x{h}'
    return True, f'{w}x{h}'


def is_image_url(url: str) -> bool:
    lower = url.lower().split('?')[0]
    return lower.endswith(IMAGE_EXT)


def label_from_url(url: str, fallback: str) -> str:
    name = Path(url.split('?')[0]).stem
    if name.lower().startswith('image-'):
        return fallback
    return name[:40] or fallback


def save_local(data: bytes, out_name: str, label: str, stickers: list[dict[str, str]]) -> None:
    ok, reason = image_ok(data)
    if not ok:
        print('SKIP', out_name, reason)
        return
    target = OUT / out_name
    target.write_bytes(data)
    stickers.append({'url': f'/stickers/{out_name}', 'label': label})
    print('KEEP', out_name, reason)


def extract_docx(path: Path, prefix: str, stickers: list[dict[str, str]]) -> None:
    with zipfile.ZipFile(path) as z:
        for name in z.namelist():
            if not name.startswith('word/media/') or name.endswith('/'):
                continue
            ext = Path(name).suffix.lower()
            if ext in {'.emf', '.wmf'}:
                continue
            out_name = f'{prefix}-{Path(name).name}'
            save_local(z.read(name), out_name, f'{path.stem} {Path(name).stem}', stickers)
        for part in ('word/document.xml', 'word/_rels/document.xml.rels'):
            try:
                text = z.read(part).decode('utf-8', errors='ignore')
            except KeyError:
                continue
            for url in URL_RE.findall(text):
                if is_image_url(url):
                    stickers.append({'url': url, 'label': label_from_url(url, path.stem)})
            for url in TARGET_RE.findall(text):
                if is_image_url(url):
                    stickers.append({'url': url, 'label': label_from_url(url, path.stem)})


def extract_pdf(path: Path, prefix: str, stickers: list[dict[str, str]]) -> None:
    try:
        import pymupdf
    except ImportError:
        print('WARN: pymupdf missing, skip pdf')
        return
    doc = pymupdf.open(path)
    for page_index, page in enumerate(doc):
        for img_index, img in enumerate(page.get_images(full=True)):
            base = doc.extract_image(img[0])
            ext = '.' + base.get('ext', 'png')
            if ext not in IMAGE_EXT:
                ext = '.png'
            out_name = f'{prefix}-p{page_index + 1}-{img_index + 1}{ext}'
            save_local(base['image'], out_name, f'{path.stem} {page_index + 1}-{img_index + 1}', stickers)


def dedupe(stickers: list[dict[str, str]]) -> list[dict[str, str]]:
    seen: set[str] = set()
    out: list[dict[str, str]] = []
    for item in stickers:
        url = item['url']
        if url in seen:
            continue
        seen.add(url)
        out.append(item)
    return out


def write_ts(stickers: list[dict[str, str]]) -> None:
    PACK_TS.write_text(
        '// Auto-generated by scripts/extract-stickers.py — do not edit by hand\n\n'
        f'export const PACK_STICKERS: {{ url: string; label: string }}[] = {json.dumps(stickers, ensure_ascii=False, indent=2)}\n',
        encoding='utf-8',
    )


def cleanup_out_dir() -> None:
    if not OUT.exists():
        return
    for path in OUT.iterdir():
        if path.is_file():
            path.unlink()


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    cleanup_out_dir()
    stickers: list[dict[str, str]] = []
    for index, source in enumerate(SOURCES, start=1):
        if not source.exists():
            print('missing', source)
            continue
        prefix = f's{index}'
        if source.suffix.lower() == '.docx':
            extract_docx(source, prefix, stickers)
        elif source.suffix.lower() == '.pdf':
            extract_pdf(source, prefix, stickers)
    merged = dedupe(stickers)
    write_ts(merged)
    print('WROTE', PACK_TS, 'count', len(merged))


if __name__ == '__main__':
    main()
