// Auto-generated by scripts/extract-stickers.py — do not edit by hand

export const PACK_STICKERS: { url: string; label: string }[] = [
  {
    "url": "https://i.postimg.cc/VvjgBzyW/15a5pesefbgapzm52mf5pq0pi.gif",
    "label": "15a5pesefbgapzm52mf5pq0pi"
  },
  {
    "url": "https://i.postimg.cc/1XxMqfdJ/1qikxf9n1mmsql3zzs0jnfzyu.gif",
    "label": "1qikxf9n1mmsql3zzs0jnfzyu"
  },
  {
    "url": "https://i.postimg.cc/cCQhMdqR/2q7etsg1qc1xtj2daffofvor.gif",
    "label": "2q7etsg1qc1xtj2daffofvor"
  },
  {
    "url": "https://i.postimg.cc/BbxpcJWg/2b197z7h2mceolvvk1zbsxxwr.gif",
    "label": "2b197z7h2mceolvvk1zbsxxwr"
  },
  {
    "url": "https://i.postimg.cc/L5dv1nWC/388pn6weqxt5227kglux43cen.gif",
    "label": "388pn6weqxt5227kglux43cen"
  },
  {
    "url": "https://i.postimg.cc/XqwLcnMs/3txhv54nejhoszepkjsny48ms.gif",
    "label": "3txhv54nejhoszepkjsny48ms"
  },
  {
    "url": "https://i.postimg.cc/T1r0qT8j/4xscqn3c0tf5bus2hckalmy71.gif",
    "label": "4xscqn3c0tf5bus2hckalmy71"
  },
  {
    "url": "https://i.postimg.cc/prNkFpSs/3vwb22fgwwxoacllinh3kw73z.gif",
    "label": "3vwb22fgwwxoacllinh3kw73z"
  },
  {
    "url": "https://i.postimg.cc/XqwLcnMg/5j71boq4y3xpzxusw0g125h14.gif",
    "label": "5j71boq4y3xpzxusw0g125h14"
  },
  {
    "url": "https://i.postimg.cc/D0q6d7V5/7dy7nsnagb10pyldos96uvynl.gif",
    "label": "7dy7nsnagb10pyldos96uvynl"
  },
  {
    "url": "https://i.postimg.cc/brQgHqXH/m9muarlejj7fu5qhhm9fw47q.gif",
    "label": "m9muarlejj7fu5qhhm9fw47q"
  },
  {
    "url": "https://i.postimg.cc/QCpmkjGj/Image-1788394453196-912.gif",
    "label": "自嘲熊动态表情包37个_小欧大王"
  },
  {
    "url": "https://i.postimg.cc/cCQhMdyW/Image-1788394458441-528.gif",
    "label": "自嘲熊动态表情包37个_小欧大王"
  },
  {
    "url": "https://i.postimg.cc/vTWhLGFY/Image-1788394456276-759.gif",
    "label": "自嘲熊动态表情包37个_小欧大王"
  },
  {
    "url": "https://i.postimg.cc/qq8wXpVH/Image-1788394460874-605.gif",
    "label": "自嘲熊动态表情包37个_小欧大王"
  },
  {
    "url": "https://i.postimg.cc/fyxCjMnn/Image-1788394462803-297.gif",
    "label": "自嘲熊动态表情包37个_小欧大王"
  },
  {
    "url": "https://i.postimg.cc/ZnrHFJtk/Image-1788394464854-528.gif",
    "label": "自嘲熊动态表情包37个_小欧大王"
  },
  {
    "url": "https://i.postimg.cc/J0bxcRwf/Image-1788394466858-682.gif",
    "label": "自嘲熊动态表情包37个_小欧大王"
  },
  {
    "url": "https://i.postimg.cc/6qdcLBsg/Image-1788394468795-605.gif",
    "label": "自嘲熊动态表情包37个_小欧大王"
  },
  {
    "url": "https://i.postimg.cc/C5j7Hwy9/Image-1788394470742-298.gif",
    "label": "自嘲熊动态表情包37个_小欧大王"
  },
  {
    "url": "https://i.postimg.cc/6qszvyPH/yp4p2ipz6un293e4xb20ro9w.gif",
    "label": "yp4p2ipz6un293e4xb20ro9w"
  },
  {
    "url": "https://i.postimg.cc/FzjpghtB/Image-1788394474982-837.gif",
    "label": "自嘲熊动态表情包37个_小欧大王"
  },
  {
    "url": "https://i.postimg.cc/0jpnd9gX/Image-1788394476985-529.gif",
    "label": "自嘲熊动态表情包37个_小欧大王"
  },
  {
    "url": "https://i.postimg.cc/ryWfLNdG/2iu212mog2ks7driv8h95us46.gif",
    "label": "2iu212mog2ks7driv8h95us46"
  },
  {
    "url": "https://i.postimg.cc/wxJwdQtQ/2m6gtbmblgtx63duuv7wiup60.gif",
    "label": "2m6gtbmblgtx63duuv7wiup60"
  },
  {
    "url": "https://i.postimg.cc/CMDcVsZk/39379jnicm5zo507fs4w9r2yr.gif",
    "label": "39379jnicm5zo507fs4w9r2yr"
  },
  {
    "url": "https://i.postimg.cc/sfSTR4BZ/243i5h94rek2ua722wan3sx0l.gif",
    "label": "243i5h94rek2ua722wan3sx0l"
  },
  {
    "url": "https://i.postimg.cc/L4fxM3qg/44tn18vh5jjnod4o5ph2gdhu7.gif",
    "label": "44tn18vh5jjnod4o5ph2gdhu7"
  },
  {
    "url": "https://i.postimg.cc/SQ8gpfXc/4ukvvfg3xuxm972jok71jcbgs.gif",
    "label": "4ukvvfg3xuxm972jok71jcbgs"
  },
  {
    "url": "https://i.postimg.cc/nrv2Ynbp/4y92rpbg4ivd3sd8yqopdb158.gif",
    "label": "4y92rpbg4ivd3sd8yqopdb158"
  },
  {
    "url": "https://i.postimg.cc/Y01RftK2/5p0jzt1tb7uw0tramqlmoj4p4.gif",
    "label": "5p0jzt1tb7uw0tramqlmoj4p4"
  },
  {
    "url": "https://i.postimg.cc/wxJwdQtk/6g0ldettk4kxkpyafu50diow.gif",
    "label": "6g0ldettk4kxkpyafu50diow"
  },
  {
    "url": "https://i.postimg.cc/gcRgPHwq/78zg1ihy5d4du91bjlaf4bk1i.gif",
    "label": "78zg1ihy5d4du91bjlaf4bk1i"
  },
  {
    "url": "https://i.postimg.cc/jqNMr4Wz/7cllhgwaek5jvgtnbusyn6r6n.gif",
    "label": "7cllhgwaek5jvgtnbusyn6r6n"
  },
  {
    "url": "https://i.postimg.cc/T2mtXJyb/rae2ashbwwbh0m9dkocp5bho.gif",
    "label": "rae2ashbwwbh0m9dkocp5bho"
  },
  {
    "url": "https://i.postimg.cc/8kWZVmFW/ykhf0ebi75uiwunv7tv4xp1r.gif",
    "label": "ykhf0ebi75uiwunv7tv4xp1r"
  },
  {
    "url": "https://i.postimg.cc/c1YFNBKm/35x1n1g3wmza8zknhtikrxrl0.gif",
    "label": "35x1n1g3wmza8zknhtikrxrl0"
  },
  {
    "url": "https://i.imgant.com/v2/Th5HyDb.jpeg",
    "label": "Th5HyDb"
  },
  {
    "url": "https://i.imgant.com/v2/ZB4Sl4t.jpeg",
    "label": "ZB4Sl4t"
  },
  {
    "url": "https://i.imgant.com/v2/2J5jWQQ.jpeg",
    "label": "2J5jWQQ"
  },
  {
    "url": "https://i.imgant.com/v2/YFve2zH.jpeg",
    "label": "YFve2zH"
  },
  {
    "url": "https://i.imgant.com/v2/s5NfDDJ.jpeg",
    "label": "s5NfDDJ"
  },
  {
    "url": "https://i.imgant.com/v2/ohIVsBk.jpeg",
    "label": "ohIVsBk"
  },
  {
    "url": "https://i.imgant.com/v2/Jhiy23b.jpeg",
    "label": "Jhiy23b"
  },
  {
    "url": "https://i.imgant.com/v2/jaY2RAK.jpeg",
    "label": "jaY2RAK"
  },
  {
    "url": "https://i.imgant.com/v2/odSMa6J.jpeg",
    "label": "odSMa6J"
  },
  {
    "url": "https://i.imgant.com/v2/BoTDKx8.jpeg",
    "label": "BoTDKx8"
  },
  {
    "url": "https://i.imgant.com/v2/gnJAMdm.jpeg",
    "label": "gnJAMdm"
  },
  {
    "url": "https://i.imgant.com/v2/7rDDyHY.jpeg",
    "label": "7rDDyHY"
  },
  {
    "url": "https://i.imgant.com/v2/n9nAbT7.jpeg",
    "label": "n9nAbT7"
  },
  {
    "url": "https://i.imgant.com/v2/F5ql4EO.jpeg",
    "label": "F5ql4EO"
  },
  {
    "url": "https://i.imgant.com/v2/KAoRBp8.jpeg",
    "label": "KAoRBp8"
  },
  {
    "url": "https://i.imgant.com/v2/kcG9AQm.jpeg",
    "label": "kcG9AQm"
  },
  {
    "url": "https://i.imgant.com/v2/q3mw5Kb.jpeg",
    "label": "q3mw5Kb"
  },
  {
    "url": "https://i.imgant.com/v2/QpnCTBk.jpeg",
    "label": "QpnCTBk"
  },
  {
    "url": "https://i.imgant.com/v2/Ae0RQYU.jpeg",
    "label": "Ae0RQYU"
  },
  {
    "url": "https://i.imgant.com/v2/IUW5VrI.jpeg",
    "label": "IUW5VrI"
  },
  {
    "url": "https://i.imgant.com/v2/4QYKIP5.jpeg",
    "label": "4QYKIP5"
  },
  {
    "url": "https://i.imgant.com/v2/pJwS2Hy.jpeg",
    "label": "pJwS2Hy"
  },
  {
    "url": "https://i.imgant.com/v2/J68dKDu.jpeg",
    "label": "J68dKDu"
  },
  {
    "url": "https://i.imgant.com/v2/pHM3CXD.jpeg",
    "label": "pHM3CXD"
  },
  {
    "url": "https://i.imgant.com/v2/Nsnzwk2.jpeg",
    "label": "Nsnzwk2"
  },
  {
    "url": "https://i.imgant.com/v2/4dsUncS.jpeg",
    "label": "4dsUncS"
  },
  {
    "url": "https://i.imgant.com/v2/HpvLiB5.jpeg",
    "label": "HpvLiB5"
  },
  {
    "url": "https://i.imgant.com/v2/uDbTMmZ.jpeg",
    "label": "uDbTMmZ"
  },
  {
    "url": "https://i.imgant.com/v2/YhB1WRo.jpeg",
    "label": "YhB1WRo"
  },
  {
    "url": "https://i.imgant.com/v2/ooA8gOi.jpeg",
    "label": "ooA8gOi"
  },
  {
    "url": "https://i.imgant.com/v2/z0TuBsM.jpeg",
    "label": "z0TuBsM"
  },
  {
    "url": "https://i.imgant.com/v2/O1xWbg9.jpeg",
    "label": "O1xWbg9"
  },
  {
    "url": "https://i.imgant.com/v2/U1m5yR2.jpeg",
    "label": "U1m5yR2"
  },
  {
    "url": "https://i.imgant.com/v2/pS4GKxx.jpeg",
    "label": "pS4GKxx"
  },
  {
    "url": "https://i.imgant.com/v2/zaQzM93.jpeg",
    "label": "zaQzM93"
  },
  {
    "url": "https://i.imgant.com/v2/w0aZv0N.jpeg",
    "label": "w0aZv0N"
  },
  {
    "url": "https://i.imgant.com/v2/2HykeQs.jpeg",
    "label": "2HykeQs"
  },
  {
    "url": "https://i.imgant.com/v2/bavm7li.jpeg",
    "label": "bavm7li"
  }
]
